---
- name: prolauno playbook GH
  hosts: gh
  become: yes

  vars_prompt:
    - name: domain_member_admin_user
      prompt: Qual seu número USP?

    - name: domain_member_password
      prompt: Qual sua senha?

  tasks:

    - name: Configura cliente sssd
      include_role:
        name: uspdev.sssd_ldap
      vars:
        sssd_ldap_realm: "smbdomain.fflch.usp.br"
        sssd_ldap_admin_password: "{{ domain_member_password }}"
        sssd_ldap_admin_user: "{{ domain_member_admin_user }}"
        
