---
- name: prolauno playbook Letras
  hosts: letras
  become: yes

  vars_prompt:
    - name: domain_member_admin_user
      prompt: Qual seu número USP?

    - name: domain_member_password
      prompt: Qual sua senha?

  tasks:

    - name: Configura cliente sssd
      include_role:
        name: uspdev.sssd_ldap
      vars:
        sssd_ldap_realm: "smbdomain.fflch.usp.br"
        sssd_ldap_admin_password: "{{ domain_member_password }}"
        sssd_ldap_admin_user: "{{ domain_member_admin_user }}"
        sssd_ldap_basedn: "dc=smbdomain,dc=fflch,dc=usp,dc=br"

    - name: Configura ntp para apontar para o SAMBA-DC
      include_role:
        name: geerlingguy.ntp
      vars:
        ntp_manage_config: true
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - 'smbdomain.fflch.usp.br'
        ntp_restrict:
          - "127.0.0.1"
          - "::1"